---
dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: podman
lint: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh
platforms:
  - name: centos7-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:centos7
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    # tmpfs:
    #   destination: "/run:rw"
    #   size: "1024k"
    #   mode: 0777
    # tmpfs:
    #   destination: "/tmp:rw"
    #   size: "1024k"
    #   mode: 0777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
  - name: centos8-${INSTANCE_UUID:-1}
    image: quay.io/centos/centos:stream8
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    # tmpfs:
    #   destination: "/run:rw"
    #   size: "1024k"
    #   mode: 0777
    # tmpfs:
    #   destination: "/tmp:rw"
    #   size: "1024k"
    #   mode: 0777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
  - name: fedora38-${INSTANCE_UUID:-1}
    image: quay.io/fedora/fedora:38
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    # tmpfs:
    #   destination: "/run:rw"
    #   size: "1024k"
    #   mode: 0777
    # tmpfs:
    #   destination: "/tmp:rw"
    #   size: "1024k"
    #   mode: 0777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: fedora39-${INSTANCE_UUID:-1}
    image: quay.io/fedora/fedora:39
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    # tmpfs:
    #   destination: "/run:rw"
    #   size: "1024k"
    #   mode: 0777
    # tmpfs:
    #   destination: "/tmp:rw"
    #   size: "1024k"
    #   mode: 0777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  inventory:
    links:
      hosts: ../resources/inventory.yml
verifier:
  name: ansible
