---
dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: podman
lint: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh
platforms:
  - name: geerlingrocky
    image: "docker.io/geerlingguy/docker-rockylinux9-ansible:latest"
    dockerfile: ../resources/Dockerfile.rockygeerling.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    priviliged: true
    pre_build_image: true
  - name: geerlingubuntu
    image: "docker.io/geerlingguy/docker-ubuntu2404-ansible:latest"
    dockerfile: ../resources/Dockerfile.ubuntugeerling.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    priviliged: true
    pre_build_image: true
  - name: geerlingdebian
    image: "docker.io/geerlingguy/docker-debian12-ansible:latest"
    dockerfile: ../resources/Dockerfile.debiangeerling.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    priviliged: true
    pre_build_image: true    
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  inventory:
    links:
      hosts: ../resources/inventory.yml
verifier:
  name: ansible
