---
- name: Converge
  hosts: localhost
  gather_facts: no
  roles:
    - hammadrauf.apache_vhosts
  vars:
    apache_vhosts_defaults_state: present
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: hammadrauf.apache_vhosts
        tasks_from: main.yml
      vars:
        apache_vhosts_defaults_state: present
